theme: jekyll-theme-cayman
title: MindScribe
description: Advanced AI-Powered Mental Health Assistant with Offline Capabilities
show_downloads: true
github:
  url: https://github.com/sanudii24/MindScribe
